# Generated by Django 5.1.1 on 2024-09-20 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_workingschedule_day_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='description',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='duration',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='npi',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='NPI must be 10 digits', regex='^\\d{10}$')]),
        ),
    ]
