# Generated by Django 5.1.1 on 2024-09-20 11:48

from django.db import migrations

def create_procedures(apps, schema_editor):
    Procedure = apps.get_model('core', 'Procedure')
    procedures = [
        'Cleaning',
        'Filling',
        'Root Canal',
        'Crown',
        'Teeth Whitening'
    ]
    for procedure_name in procedures:
        Procedure.objects.get_or_create(name=procedure_name)

def reverse_procedures(apps, schema_editor):
    Procedure = apps.get_model('core', 'Procedure')
    Procedure.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_procedure_description_and_more'),
    ]

    operations = [
        migrations.RunPython(create_procedures, reverse_procedures),
    ]
