# Generated by Django 5.1.1 on 2024-09-20 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_populate_procedures'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.IntegerField(choices=[(9, '9:00 AM'), (10, '10:00 AM'), (11, '11:00 AM'), (12, '12:00 PM'), (13, '1:00 PM'), (14, '2:00 PM'), (15, '3:00 PM'), (16, '4:00 PM')])),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='core.doctorclinicaffiliation')),
            ],
            options={
                'unique_together': {('affiliation', 'day_of_week', 'start_time')},
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_slot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.timeslot'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('time_slot', 'date')},
        ),
        migrations.DeleteModel(
            name='WorkingSchedule',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
    ]
