# Generated by Django 5.1.1 on 2024-09-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_visit_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.IntegerField(choices=[(9, '9:00 AM'), (10, '10:00 AM'), (11, '11:00 AM'), (12, '12:00 PM'), (13, '1:00 PM'), (14, '2:00 PM'), (15, '3:00 PM'), (16, '4:00 PM'), (17, '5:00 PM')]),
        ),
    ]
