# Generated by Django 5.1.1 on 2024-09-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_timeslot_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('name', 'date_of_birth', 'ssn_last_4')},
        ),
    ]
