# Generated by Django 5.1.1 on 2024-09-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_clinic_email_alter_clinic_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')]),
        ),
    ]
